default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["dbuser"] %>
  password: <%= ENV["dbpass"] %>
  host: <%= ENV["dbhost"] %>

development:
  <<: *default
  database: <%= ENV["dbname"] %>

staging:
  <<: *default
  database: aeksion_staging

test:
  <<: *default
  database: aeksion_test

production:
  <<: *default
  database: aeksion
  username: aeksion
  password: <%= ENV["AEKSION_DATABASE_PASSWORD"] %>
