name: PRs to staging
on: 
  pull_request:
    branches: [staging]
    types: [closed]
jobs:
  merge-main-back-to-develop:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge staging back to dev
      run: |
          git fetch --unshallow
          git switch staging
          git merge --no-ff develop -m "[bot] gh merge develop into staging"